# Generated by Django 5.1.4 on 2024-12-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_todo_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Sunnyvale', max_length=100),
        ),
    ]
